name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Authorize gcloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{secrets.GCLOUD_AUTH}}
    - name: Build docker image
      uses: actions/gcloud/cli@master
      with:
        args: --project bendik-dev builds submit --tag gcr.io/bendik-dev/bendik-dev

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy new revision
      uses: actions/gcloud/cli@master
      with:
        args: --project bendik-dev beta run deploy bendik-dev --platform managed --region us-central1 --allow-unauthenticated --image gcr.io/bendik-dev/bendik-dev
