name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Authorize gcloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{secrets.GCLOUD_AUTH}}
    - name: Build docker image
      uses: actions/gcloud/cli@master
      with:
        args: builds submit --tag gcr.io/bendik-dev/bendik-dev
